apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- envs:
  - .env
  name: settings
  type: Opaque

resources:
- ../../base

patchesJson6902:
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    name: front
  patch: |-
    [{ "op": "replace", "path": "/spec/routes/0/match", "value": "Host(`play.workadventure.suse.net`)" }]
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    name: pusher
  patch: |-
    [{ "op": "replace", "path": "/spec/routes/0/match", "value": "Host(`pusher.workadventure.suse.net`)" }]
# - target:
#     group: traefik.containo.us
#     version: v1alpha1
#     kind: IngressRoute
#     name: back
#   patch: |-
#     [{ "op": "replace", "path": "/spec/routes/0/match", "value": "Host(`api.workadventure.suse.net`)" }]
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    name: uploader
  patch: |-
    [{ "op": "replace", "path": "/spec/routes/0/match", "value": "Host(`uploader.workadventure.suse.net`)" }]

patches:
# - target:
#     group: traefik.containo.us
#     version: v1alpha1
#     kind: IngressRoute
#   patch: |-
#      [{ "op": "replace", "path": "/spec/tls/certResolver", "value": "myresolver" }]
- path: replica-count.yaml
