apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: back
    spec:
      containers:
        - args:
            - yarn
            - run
            - runprod
          env:
            - name: ADMIN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: ADMIN_API_TOKEN
                  optional: true
            - name: ADMIN_API_URL
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: ADMIN_API_URL
                  optional: true
            # - name: ALLOW_ARTILLERY
            #   valueFrom:
            #     secretKeyRef:
            #       name: settings
            #       key: ALLOW_ARTILLERY
            #       optional: true
            # - name: DEBUG
            #   valueFrom:
            #     secretKeyRef:
            #       name: settings
            #       key: DEBUG
            #       optional: true
            - name: JITSI_ISS
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: JITSI_ISS
            - name: JITSI_URL
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: JITSI_URL
            - name: SECRET_JITSI_KEY
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: SECRET_JITSI_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: SECRET_KEY
            - name: TURN_STATIC_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: settings
                  key: TURN_STATIC_AUTH_SECRET
                  optional: true
          image: ghcr.io/workadventure-suse/workadventure-back:hackweek-prep
          name: back
          resources: {}
      restartPolicy: Always
status: {}
